<?php

return [
    'author' => 'Tiago Mendes',
    'author_website' => 'http://mendes.com.pt',
    'site_name' => 'Domingo às Dez',
    'site_domain' => 'domingoasdez.com',
    'site_url' => 'http://domingoasdez.com',
    'site_email' => 'geral@domingoasdez.com',
    'register_enable' => true,
    'login_enable' => true,
    'social_logins' => filter_var(env('SOCIAL_LOGINS_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'default_profile_pic' => '/images/default-profile.png',
    'site_logo' => '/images/domingo.png',
    'results_per_page' => 25,
    'default_emblem' => '/images/default-emblem.png',
    'media_images_folder' => '/storage/media/images',
    'media_videos_folder' => '/storage/media/videos',
    'media_other_folder' => '/storage/media/files',
    'media_thumbnails' => '/storage/media/thumbnails',
    'dashboard_sidenav_image' => '/images/sidenav_image.jpg',
    'site_sidenav_image' => '/images/sidenav_image.jpg',
    'site_sidenav_image_no_login' => '/images/sidenav_image_blur.jpg',
    'user_avatars_path' => '/storage/uploads/users/avatars',
    'send_exception_to_mail' => env('SEND_EXCEPTION_TO_MAIL', 'false'),
    'exception_notification_email' => env('EXCEPTION_NOTIFICATION_EMAIL', 'tiagoomendess@gmail.com'),
    'adsense_enabled' => env('ADSENSE_ENABLED', true),
    'google_analytics_enabled' => env('GOOGLE_ANALYTICS_ENABLED', true),
    'google_login_enabled' => filter_var(env('GOOGLE_LOGIN_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'facebook_login_enabled' => filter_var(env('FACEBOOK_LOGIN_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'apple_login_enabled' => filter_var(env('APPLE_LOGIN_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    // false: every visitor. true: only logged-in users.
    'new_site_prompt_logged_in_only' => filter_var(env('NEW_SITE_PROMPT_LOGGED_IN_ONLY', false), FILTER_VALIDATE_BOOLEAN),
    'new_site_url' => env('NEW_SITE_URL', 'https://app.domingoasdez.com'),
];
